name: Wooler
version: 1.0.1
author: HimbeersaftLP
api:
- 1.14.0
- 2.0.0
main: HimbeersaftLP\Wooler\main
commands:
    wool:
        usage: "/wool <id|give|list> [id] [count]"
        description: "Main command of Wooler."
permissions:
    wooler.id:
        default: true
        description: "Permission for /woll id"
    wooler.give:
        default: op
        description: "Permission for /wool give"
    wooler.list:
        default: true
        description: "Permission for /wool list"
