name: ColorId
version: 2.0.1
author: HimbeersaftLP
api: [1.14.0, 2.0.0, 3.0.0, 3.0.0-ALPHA1]
main: HimbeersaftLP\ColorId\main
commands:
    wool:
        usage: "/wool <id|give|list> [id] [count]"
        description: "Get IDs of wool and give yourself wool."
    clay:
        usage: "/clay <id|give|list> [id] [count]"
        description: "Get IDs of clay and give yourself clay."
permissions:
    wooler.id:
        default: true
        description: "Permission for /wool id"
    wooler.give:
        default: op
        description: "Permission for /wool give"
    wooler.list:
        default: true
        description: "Permission for /wool list"
    clayer.id:
        default: true
        description: "Permission for /clay id"
    clayer.give:
        default: op
        description: "Permission for /clay give"
    clayer.list:
        default: true
        description: "Permission for /clay list"
